module.exports = {
    SAVE_CONTACT: 'SAVE_CONTACT',
    RECEIVE_CONTACT: 'RECEIVE_CONTACT ',
    REMOVE_CONTACT: 'REMOVE_CONTACT',
    EDIT_CONTACT: 'EDIT_CONTACT',
    UPDATE_CONTACT: 'UPDATE_CONTACT',

    ADD_NOTE: 'ADD_NOTE',
    RECEIVE_NOTES: 'RECEIVE_NOTES',
    REMOVE_NOTE: 'REMOVE_NOTE',
    EDIT_NOTE: 'EDIT_NOTE',
    UPDATE_NOTE: 'UPDATE_NOTE'
};