module.exports = {
    SAVE_CONTACT: 'SAVE_CONTACT',
    RECEIVE_CONTACT: 'RECEIVE_CONTACT ',
    REMOVE_CONTACT: 'REMOVE_CONTACT',
    EDIT_CONTACT: 'EDIT_CONTACT',
    UPDATE_CONTACT: 'UPDATE_CONTACT',
    ADD_NOTE: 'ADD_NOTE'
};